openapi: 3.0.0
info:
  title: ECC Ministry Application API
  description: 'API for Coding Challenge (IS24 - Full Stack Developer at Ministry of Education & Child Care)'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: Server for development
paths:
  /products:
    get:
      summary: Returns a list of products.
      responses:
        '200':    
          description: A JSON array of products
          content:
            application/json:
              schema: 
                type: array